import { Aluno } from '../../models/aluno/aluno';
export const LISTA_ALUNOS_EXEMPLO: Aluno[] = [
    {
      id_aluno: '1',
      nome: 'Fulano de Tal dos Anzóis',
      email: 'fulanodetaldosanzois@gmail.com',
      data_nascimento: '2019-06-06',
      data_matricula: '2019-06-06',
      sexo: 'Masculino',
      grupo: '0',
      id_professor: '18',
      id_usuario: '30814',
      id_iugu: null,
      hash: '3AhyhFrAJShxyNpFFDO9biDjst9w9Sew0mBC2N62iArzh4rRy',
      ativo: '1',
      visivel: '1',
      usuario: {
        id_usuario: '1',
        nome: 'Fulano de Tal dos Anzóis',
        login: 'fulanodetaldosanzois',
        senha: 'da39a3ee5e6b4b0d3255bfef95601890afd80709',
        email: 'fulanodetaldosanzois@gmail.com',
        hash: 'h6uNSU09AQVnyS70nIqCQK2HXWMWdnVNkEmvSxEre0f3lrgy',
        ativo: '1',
        player_id: '',
        id_tipo_usuario: '3',
        data_matricula: '2019-06-06',
        link_foto: null,
        ultimo_login: null
      }
    },
    {
      id_aluno: '2',
      nome: 'Maria de Tal dos Anzóis',
      email: 'mariadetaldosanzois@gmail.com',
      data_nascimento: '2019-06-06',
      data_matricula: '2019-06-06',
      sexo: 'Feminino',
      grupo: '0',
      id_professor: '18',
      id_usuario: '30814',
      id_iugu: null,
      hash: '3AhyhFrAJShxyNpFFDO9biDjst9w9Sew0mBC2N62iArzh4rRy',
      ativo: '1',
      visivel: '1',
      usuario: {
        id_usuario: '2',
        nome: 'Maria de Tal dos Anzóis',
        login: 'mariadetal',
        senha: 'da39a3ee5e6b4b0d3255bfef95601890afd80709',
        email: 'mariadetaldosanzois@gmail.com',
        hash: 'h6uNSU09AQVnyS70nIqCQK2HXWMWdnVNkEmvSxEre0f3lrgy',
        ativo: '1',
        player_id: '',
        id_tipo_usuario: '3',
        data_matricula: '2019-06-06',
        link_foto: null,
        ultimo_login: null
      }
    },
];
